[workspace]
resolver = "2"
members = [
    "libninja",
    "macro",
    "core",
    "mir",
    "hir"
]
exclude = [
    "commercial",
]

#[patch.crates-io]
#serde_derive = { git = "https://github.com/kurtbuilds/serde" }
#openapiv3-extended = { path = "../openapiv3" }