name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


defaults:
  run:
    shell: bash

jobs:
  run-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - run: cargo install just
    - name: Install checkexec
      shell: bash
      run: |
        which checkexec && exit 0
        curl -LO https://github.com/kurtbuilds/checkexec/releases/download/v0.2.0/checkexec-v0.2.0-x86_64-unknown-linux-musl.tar.gz
        tar xvzf checkexec-v0.2.0-x86_64-unknown-linux-musl.tar.gz checkexec
        chmod +x checkexec
        sudo mv checkexec /usr/local/bin
    - run: just dummy_commercial
    - run: cargo test
